package info.kfgodel.jspek.api.exceptions;

/**
 * This type represents a runnable code tahta fails with a throwable
 * @param <X> Type of expected exception
 * Created by kfgodel on 29/04/16.
 */
public interface FailingRunnable<X extends Throwable> {

  /**
   * Executes this code to fail with the expected exception
   *
   * @throws X The exception generated by this code
   */
  void run() throws X;
}
